import type { NextPage } from 'next';
import Head from 'next/head';
import About from './components/About';
import Masthead from './components/masthead';
import Skills from './components/Skills';
import Footer from './components/Footer';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Masthead />
			<About />
			<Skills />
			<Footer />
		</div>
	);
};

export default Home;
